services:

  auth-microfrontend:
    build:
      context: auth-microfrontend
      dockerfile: ../Dockerfile.auth-microfrontend
    networks:
      - mestanet
  
  profile-microfrontend:
    build:
      context: profile-microfrontend
      dockerfile: ../Dockerfile.profile-microfrontend
    networks:
      - mestanet
  
  card-add-microfrontend:
    build:
      context: card-add-microfrontend
      dockerfile: ../Dockerfile.card-add-microfrontend
    networks:
      - mestanet

  frontend:
    build:
      context: frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - 3000:8080
    networks:
      - mestanet
    depends_on:
      - auth-microfrontend 
      - profile-microfrontend
      - card-add-microfrontend 

networks:
  mestanet:
    driver: bridge